#!/usr/bin/env python3
"""Set up agent-brigade in this repo, or switch profile/size later. Never overwrites a file you've edited.

  python3 core/scripts/init.py --profile hackathon --full
  python3 core/scripts/init.py --profile project --lite

On a fresh copy of the kit (kit.toml has kit_dev = true) it removes the kit's own dev/ folder first.
Then it writes kit.toml, copies the spec templates into specs/, installs CI, the PR template and the pre-commit
hook, and adds the profile's files (gates.toml, or NOW.md + milestones.toml + review-paths.toml).
Run it again with a different --profile or --lite/--full to upgrade (core/docs/upgrading.md).
"""

import re
import shutil
import stat
import subprocess
import sys
from pathlib import Path

from kitlib import find_root, git, load_config, load_toml, parser, specs_dir

KIT = Path(__file__).resolve().parents[2]  # the kit's own files, wherever init.py lives
CODEOWNERS_HEADER = "# Generated by agent-brigade init.py from specs/review-paths.toml. Edit that file, not this one."

KIT_TOML = """# agent-brigade settings. Every key and default: core/docs/config.md
profile = "{profile}"
size = "{size}"

[paths]
specs = "specs"
changes = "changes"
reports = "reports"

[ownership]
frozen = ["AGENTS.md", "CLAUDE.md", "kit.toml", ".github/", "core/", "profiles/"]
open = [{open}]

[agents]
max_parallel = {parallel}
reporter = ""

[pr]
max_lines = 400

[release]
url = ""                 # your production origin, e.g. https://my-app.example
health_path = "/api/health"
smoke_paths = ["/"]
snapshot_paths = ["/"]

[watchdog]
restart = ""             # e.g. a tmux or agent-CLI command; see core/docs/integrations/
alert = ""               # e.g. a curl to ntfy.sh; see core/docs/remote.md
"""


def copy_new(src: Path, dest: Path, created: list[str], root: Path) -> None:
    """Copy src to dest unless dest exists."""
    if dest.exists():
        return
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(src, dest)
    created.append(dest.relative_to(root).as_posix())


def is_fresh_copy(root: Path) -> bool:
    if not (root / ".git").exists():
        return True
    count = git(root, "rev-list", "--count", "HEAD", check=False).strip()
    return not count or int(count) <= 1


def write_codeowners(root: Path, cfg: dict, created: list[str]) -> None:
    data = load_toml(specs_dir(root, cfg) / "review-paths.toml") or {}
    entries = data.get("path", [])
    dest = root / ".github" / "CODEOWNERS"
    if not entries or (dest.exists() and CODEOWNERS_HEADER not in dest.read_text()):
        return
    lines = [CODEOWNERS_HEADER]
    for e in entries:
        lines.append(f"/{e['prefix'].lstrip('/')} {' '.join(e['owners'])}")
    dest.parent.mkdir(parents=True, exist_ok=True)
    existed = dest.exists()
    dest.write_text("\n".join(lines) + "\n")
    if not existed:
        created.append(".github/CODEOWNERS")


def install_hook(root: Path) -> str:
    hook = root / "core" / "hooks" / "pre-commit"
    if hook.exists():
        hook.chmod(hook.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    if not (root / ".git").exists():
        return "not a git repo yet: after `git init`, run `git config core.hooksPath core/hooks`"
    r = subprocess.run(["git", "config", "core.hooksPath", "core/hooks"], cwd=root, capture_output=True, text=True)
    return "pre-commit hook on (core/hooks)" if r.returncode == 0 else f"hook not installed: {r.stderr.strip()}"


def main(argv=None) -> int:
    ap = parser(__doc__)
    ap.add_argument("--profile", required=True, choices=["hackathon", "project"])
    size = ap.add_mutually_exclusive_group()
    size.add_argument("--lite", dest="size", action="store_const", const="lite", help="one agent, least ceremony")
    size.add_argument("--full", dest="size", action="store_const", const="full", help="parallel agents (default)")
    ap.add_argument("--fresh", action="store_true", help="treat this as a fresh kit copy even if it has git history")
    args = ap.parse_args(argv)
    size_choice = args.size or "full"
    root = Path(args.root).resolve() if args.root else find_root()
    toml_path = root / "kit.toml"
    old = load_toml(toml_path) or {}
    created: list[str] = []

    if old.get("kit_dev"):
        if not (args.fresh or is_fresh_copy(root)):
            print("init: this looks like the agent-brigade source repo itself (kit_dev = true, with history).\n"
                  "init: run it in your copy instead, or pass --fresh if this really is a new copy.")
            return 2
        if (root / "dev").exists():
            shutil.rmtree(root / "dev")
            print("init: removed the kit's own dev/ folder")
        old = {}

    if not old:
        open_paths = '"NOW.md"' if args.profile == "project" else ""
        toml_path.write_text(KIT_TOML.format(profile=args.profile, size=size_choice, open=open_paths,
                                             parallel=1 if size_choice == "lite" else 3))
        created.append("kit.toml")
    else:
        text = toml_path.read_text()
        text = re.sub(r'(?m)^profile\s*=.*$', f'profile = "{args.profile}"', text)
        text = re.sub(r'(?m)^size\s*=.*$', f'size = "{size_choice}"', text)
        if args.profile == "project" and "NOW.md" not in text:
            print('init: tip: add "NOW.md" to [ownership].open in kit.toml so any PR may update it')
        toml_path.write_text(text)
        print(f"init: kit.toml now {args.profile}/{size_choice} (was {old.get('profile')}/{old.get('size', 'full')})")

    cfg = load_config(root)
    specs = specs_dir(root, cfg)
    templates = KIT / "core" / "specs"
    for src in sorted(p for p in templates.rglob("*") if p.is_file()):
        copy_new(src, specs / src.relative_to(templates), created, root)
    for d in (cfg["paths"]["changes"], cfg["paths"]["reports"]):
        if not (root / d).exists():
            (root / d).mkdir(parents=True)
            (root / d / ".gitkeep").touch()  # so git tracks the empty folder
            created.append(f"{d}/")
    copy_new(KIT / "core" / "ci" / "ci.yml", root / ".github" / "workflows" / "ci.yml", created, root)
    copy_new(KIT / "core" / "ci" / "pull_request_template.md", root / ".github" / "pull_request_template.md", created, root)

    prof = KIT / "profiles" / args.profile
    if args.profile == "hackathon":
        copy_new(prof / "gates.toml", specs / "gates.toml", created, root)
        (specs / "context").mkdir(parents=True, exist_ok=True)
    else:
        copy_new(prof / "NOW.md", root / "NOW.md", created, root)
        copy_new(prof / "milestones.toml", specs / "milestones.toml", created, root)
        copy_new(prof / "review-paths.toml", specs / "review-paths.toml", created, root)
        write_codeowners(root, cfg, created)

    gi = root / ".gitignore"
    lines = gi.read_text().splitlines() if gi.exists() else []
    missing = [x for x in (".agent-brigade/", ".env", ".env.*") if x not in lines]
    if missing:
        gi.write_text("\n".join(lines + missing) + "\n")

    for c in created:
        print(f"init: created {c}")
    print(f"init: {install_hook(root)}")
    entry = "profiles/hackathon/preflight.md" if args.profile == "hackathon" else "NOW.md"
    print(f"init: done ({args.profile}/{size_choice}). Next: fill in {cfg['paths']['specs']}/mission.md, then {entry}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
